CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY '1234';

REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'appuser'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE
ON price_db.*
TO 'appuser'@'%';

FLUSH PRIVILEGES;